### ISSUE TITLE
项目用的vue2

### ISSUE THREAD

**Issue by lrving-11** [maliangnansheng/bbs-vue3-ui#1]

**Comment by lrving-11** [comment]
有vue3的版本吗

**Comment by maliangnansheng** [comment]
> 有vue3的版本吗

这个项目是vue3哈，是可以使用vue3的特性的，在vue2基础上升级而来的（兼容了vue2的写法）
这是vue2：https://github.com/maliangnansheng/bbs-vue3-ui

**Comment by maliangnansheng** [comment]
> 有vue3的版本吗

可以看看[package.json](https://github.com/maliangnansheng/bbs-vue3-ui/blob/master/package.json)
